# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import operation_pb2 as operation__pb2


class OperationStub(object):
  """The operation service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/operation.Operation/Add',
        request_serializer=operation__pb2.OpRequest.SerializeToString,
        response_deserializer=operation__pb2.OpReply.FromString,
        )


class OperationServicer(object):
  """The operation service definition
  """

  def Add(self, request, context):
    """Adds two numbers
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OperationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=operation__pb2.OpRequest.FromString,
          response_serializer=operation__pb2.OpReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'operation.Operation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
