# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlframework.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlframework.proto',
  package='dlframework',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x64lframework.proto\x12\x0b\x64lframework\"\x1a\n\tDlRequest\x12\r\n\x05image\x18\x01 \x02(\t\"\x1d\n\x07\x44lReply\x12\x12\n\nprediction\x18\x01 \x02(\t2H\n\x0b\x44lframework\x12\x39\n\x07Predict\x12\x16.dlframework.DlRequest\x1a\x14.dlframework.DlReply\"\x00\x42.\n\x1cio.grpc.examples.dlframeworkB\x0c\x44lFrameProtoP\x01')
)




_DLREQUEST = _descriptor.Descriptor(
  name='DlRequest',
  full_name='dlframework.DlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='dlframework.DlRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=60,
)


_DLREPLY = _descriptor.Descriptor(
  name='DlReply',
  full_name='dlframework.DlReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prediction', full_name='dlframework.DlReply.prediction', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['DlRequest'] = _DLREQUEST
DESCRIPTOR.message_types_by_name['DlReply'] = _DLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DlRequest = _reflection.GeneratedProtocolMessageType('DlRequest', (_message.Message,), dict(
  DESCRIPTOR = _DLREQUEST,
  __module__ = 'dlframework_pb2'
  # @@protoc_insertion_point(class_scope:dlframework.DlRequest)
  ))
_sym_db.RegisterMessage(DlRequest)

DlReply = _reflection.GeneratedProtocolMessageType('DlReply', (_message.Message,), dict(
  DESCRIPTOR = _DLREPLY,
  __module__ = 'dlframework_pb2'
  # @@protoc_insertion_point(class_scope:dlframework.DlReply)
  ))
_sym_db.RegisterMessage(DlReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.grpc.examples.dlframeworkB\014DlFrameProtoP\001'))

_DLFRAMEWORK = _descriptor.ServiceDescriptor(
  name='Dlframework',
  full_name='dlframework.Dlframework',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=93,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='dlframework.Dlframework.Predict',
    index=0,
    containing_service=None,
    input_type=_DLREQUEST,
    output_type=_DLREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DLFRAMEWORK)

DESCRIPTOR.services_by_name['Dlframework'] = _DLFRAMEWORK

# @@protoc_insertion_point(module_scope)
