# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dlframework_pb2 as dlframework__pb2


class DlframeworkStub(object):
  """dlframework service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/dlframework.Dlframework/Predict',
        request_serializer=dlframework__pb2.DlRequest.SerializeToString,
        response_deserializer=dlframework__pb2.DlReply.FromString,
        )


class DlframeworkServicer(object):
  """dlframework service definition
  """

  def Predict(self, request, context):
    """Predict class for an image
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DlframeworkServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=dlframework__pb2.DlRequest.FromString,
          response_serializer=dlframework__pb2.DlReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlframework.Dlframework', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
